name: Main
on:
  push:
    branches:
      - fork-for-tmp-release
jobs:
  # Global
  # ================================================

  eslint-16:
    name: 'ESLint Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn lint

  # Node 16
  # ================================================

  build-16:
    name: 'Build Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - run: yarn build:examples

  tests-16:
    name: 'Mocha Tests Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: yarn test

  # Node 14
  # ================================================

  build-14:
    name: 'Build Node 14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - run: yarn build:examples

  tests-14:
    name: 'Mocha Tests Node 14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: yarn test

  publish:
    runs-on: ubuntu-latest
    name: Publish to npm registry
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install --ignore-scripts --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          # prepublishOnly compiles the ts files
          npm publish --access public
